services:
  mysql:
    image: mysql:8.0
    container_name: gestor-biblioteca-mysql
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: gestor_biblioteca
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptu_password" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: gestor-biblioteca-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gestor_biblioteca
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sasa

volumes:
  mysql_data: